"""add relation with workouts

Revision ID: 2ffb8dc45bc6
Revises: 96bea9469dde
Create Date: 2026-10-02 18:41:17.409797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ffb8dc45bc6'
down_revision: Union[str, Sequence[str], None] = '96bea9469dde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workouts', sa.Column('workout_plan_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'workouts', 'workout_plan', ['workout_plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'workouts', type_='foreignkey')
    op.drop_column('workouts', 'workout_plan_id')
    # ### end Alembic commands ###
