"""add weight and reps

Revision ID: 96bea9469dde
Revises: 6028844973e5
Create Date: 2026-10-01 11:45:02.898474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96bea9469dde'
down_revision: Union[str, Sequence[str], None] = '6028844973e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workoutplan_exercise', sa.Column('weight', sa.Float(), nullable=True))
    op.add_column('workoutplan_exercise', sa.Column('reps', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workoutplan_exercise', 'reps')
    op.drop_column('workoutplan_exercise', 'weight')
    # ### end Alembic commands ###
